### ISSUE TITLE
duplicate id: editor-dialog-title

### ISSUE THREAD

**Issue by illume** [kubernetes-sigs/headlamp#1230]
When editing something... There is a duplicate id: "editor-dialog-title"

```REACT_APP_SKIP_A11Y=false make run-frontend```
http://localhost:3000/c/minikube/storage/classes/standard

![Screenshot 2023-07-10 134601](https://github.com/headlamp-k8s/headlamp/assets/9541/28c03ccc-53b2-432f-88e0-47c08cb36e46)

**Comment by knrt10** [comment]
I can reproduce this, working on it.
