### ISSUE TITLE
app: `npm run lint` picks up compiled JavaScript and gives false reports

### ISSUE THREAD

**Issue by illume** [kubernetes-sigs/headlamp#1381]
1) Compile the app JavaScript
```
cd app
npm run build
cd ..
```

2) Run the linter:
```
cd frontend
npm run lint
```

![image](https://github.com/headlamp-k8s/headlamp/assets/9541/d273962c-12af-420d-95ee-8cf5e62a3662)

**Comment by tazo90** [comment]
@illume I think we can close this issue. The `.eslintignore` now contains exclusions for the above files.
