### ISSUE TITLE
Improve API documentation + website links

### ISSUE THREAD

**Issue by sniok** [kubernetes-sigs/headlamp#2227]
After updating typedoc, the format of the generated documentation has changed. See https://github.com/headlamp-k8s/headlamp/pull/2219

Things that need to be done after the upgrade:
- [x] Regenerate `docs/api/`
- [x] Automate docs generation(?)
- [x] Update website links to the API doc
- [x] Configure typedoc markdown plugin to improve representation in docusaurus

Blog:
- [x] Make sure that the old style URLs (with YYYY/MM/BLOG_POST_FILE_NAME) still work (old link example: https://headlamp.dev/blog/2022/08/getting-started-with-headlamp-using-minikube/ ) PR: https://github.com/headlamp-k8s/headlamp-website/pull/46

**Comment by illume** [comment]
The API links are currently 404 in our plugin guide.

https://headlamp.dev/docs/latest/development/plugins/functionality

Note, these links are broken from before typedocs have been updated. Haven't checked the new typedocs config. Maybe because the new website renders markdown/links differently?

**Comment by sniok** [comment]
Links were updated in #2247, docs generation is already automated in headlamp-website repo.

**Comment by joaquimrocha** [comment]
This PR fixes the blog redirection: https://github.com/headlamp-k8s/headlamp-website/pull/46
